'use strict';
const DEFAULT_NAMES=['Aidan Redgwick','Andy Bellhouse','Brian Hayes','Cody Moss','Daniel Ingleson','Davey','Eesa Mahmood','Eoghan Carroll','Finlay Sanderson','Glen Hanson','Jim Herron','Kai Hepworth','Kosta Sefer','Lee Royal','Maris Caune','Robert Bosek (Bobby)','Zohaib Akhtar'];
const KEY='wms-timesheet-printer-v1';
const $=id=>document.getElementById(id);
const escapeHTML=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function parseDate(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return null;const d=new Date(value+'T12:00:00');return Number.isNaN(d.getTime())||dateISO(d)!==value?null:d;}
function dateISO(d){return `${String(d.getFullYear()).padStart(4,'0')}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function addDays(value,n){const d=parseDate(value);if(!d)return '';d.setDate(d.getDate()+n);return dateISO(d);}
function monday(){const d=new Date();d.setDate(d.getDate()-(d.getDay()+6)%7);return dateISO(d);}
function format(value,options){return parseDate(value).toLocaleDateString('en-GB',options);}
let state={names:[...DEFAULT_NAMES],selected:[...DEFAULT_NAMES],days:[0,1,2,3,4],week:monday()};
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&Array.isArray(saved.names)&&saved.names.length&&saved.names.every(n=>typeof n==='string'&&n.trim()&&n.length<=100)&&Array.isArray(saved.selected)&&Array.isArray(saved.days)){state={names:[...new Set(saved.names)],selected:saved.selected.filter(n=>saved.names.includes(n)),days:[...new Set(saved.days.filter(n=>Number.isInteger(n)&&n>=0&&n<7))],week:parseDate(saved.week)?saved.week:monday()};}}catch{}
let page=0;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('storageError').textContent='';}catch{$('storageError').textContent='This browser could not save your choices. You can still print during this session.';}}
function jobs(){const d=parseDate(state.week);if(!d||d.getDay()!==1||state.week<'1900-01-01'||state.week>'9998-12-31')return [];return state.names.filter(n=>state.selected.includes(n)).flatMap(name=>[...state.days].sort((a,b)=>a-b).map(day=>({name,date:addDays(state.week,day)})));}
// Print continuously in employee/date order without separator pages.
function printBatch(){return jobs();}
function printHTML(job){return formHTML(job);}
function previewHTML(job){return formHTML(job);}
const codes=[['RW','Reworks'],['L','Loading/Unloading vans for site'],['AM','Awaiting material'],['N','No work allocated'],['T','Training/meetings'],['S','Stores tasks'],['M','Maintenance'],['E','Equipment/tools'],['B1','Morning break'],['B2','Afternoon break']];
function formHTML(job){return `<article class="sheet"><div class="sheet-head"><h3>Daily Production Labour Booking Form</h3><img class="sheet-logo" src="wms-logo.png" alt="WMS Waites Mechanical Services"></div><div class="identity"><div><b>Name:</b> ${escapeHTML(job.name)}</div><div><b>Date:</b> ${format(job.date,{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}</div></div><div class="form-body"><div><table class="booking"><thead><tr><th></th><th>Time</th><th>Code</th><th>Project Number (e.g. W4052)</th><th>Workshop (W) or Site (S)</th></tr></thead><tbody>${Array.from({length:10},()=>'<tr><td>Start</td><td></td><td rowspan="2"></td><td rowspan="2"></td><td rowspan="2"></td></tr><tr><td>Finish</td><td></td></tr>').join('')}</tbody></table><div class="total">Total daily hours: __________________</div></div><div class="form-sidebar"><div class="allowances"><h4>Tick if applicable</h4>${['Weld hire','Mileage (Own vehicle)','Travel','Overnight meal allowance abroad','Overnight meal allowance UK','Items bought for company using own money (Attach receipt to timesheet)'].map(t=>`<div class="allowance"><span class="tick"></span><span>${t}</span></div>`).join('')}</div><div class="codes"><div><h4>CODES</h4><table><thead><tr><th>Code</th><th>Description</th></tr></thead><tbody>${codes.map(([c,d])=>`<tr><td>${c}</td><td>${d}</td></tr>`).join('')}</tbody></table></div><div><p>Relevant job number must be included on timesheet.</p></div></div></div></div><div class="notices">ALL BREAKS MUST BE TAKEN – ANYONE WHO WORKS THROUGH THEIR BREAKS WILL NOT BE PAID FOR IT<br>ALL SUBCONTRACTORS MUST SEND RACHEL THEIR TIMESHEET NO LATER THAN 10AM MONDAY</div></article>`;}
function renderEmployees(){$('employees').innerHTML=state.names.map((name,i)=>`<label class="employee"><input type="checkbox" data-employee="${i}" ${state.selected.includes(name)?'checked':''}><span>${escapeHTML(name)}</span></label>`).join('');}
function renderDays(){const valid=parseDate(state.week);$('days').innerHTML=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((name,i)=>`<label class="day"><input type="checkbox" data-day="${i}" ${state.days.includes(i)?'checked':''}><span>${name}<small>${valid?format(addDays(state.week,i),{day:'2-digit',month:'short'}):'Choose a week'}</small></span></label>`).join('');}
function render(){const forms=jobs();const batch=printBatch();page=Math.max(0,Math.min(page,batch.length-1));$('selectedCount').textContent=`${state.selected.length} of ${state.names.length}`;$('summary').textContent=`${forms.length} timesheet${forms.length===1?'':'s'} · ${Math.ceil(batch.length/2)} sheets double-sided`;$('summaryDetail').textContent=`${state.selected.length} employees × ${state.days.length} days · Continuous printing, no blank pages`;$('print').disabled=!batch.length;$('back').disabled=page===0||!batch.length;$('forward').disabled=page>=batch.length-1;$('pageNumber').textContent=batch.length?`Side ${page+1} / ${batch.length} · ${page%2?'Back':'Front'}`:'0 / 0';$('dateError').textContent=!parseDate(state.week)?'Choose a valid week start date.':parseDate(state.week).getDay()!==1?'Choose a Monday for the start of the week.':'';$('preview').innerHTML=batch.length?previewHTML(batch[page]):'<div class="empty">Choose a Monday, at least one employee, and at least one day to preview your timesheets.</div>';}
function changed(){page=0;save();render();}
$('week').value=state.week;renderDays();renderEmployees();render();
$('employees').addEventListener('change',e=>{if(!e.target.matches('[data-employee]'))return;const name=state.names[Number(e.target.dataset.employee)];state.selected=e.target.checked?[...new Set([...state.selected,name])]:state.selected.filter(n=>n!==name);changed();});
$('days').addEventListener('change',e=>{if(!e.target.matches('[data-day]'))return;const day=Number(e.target.dataset.day);state.days=e.target.checked?[...new Set([...state.days,day])]:state.days.filter(n=>n!==day);changed();});
$('week').addEventListener('change',()=>{state.week=$('week').value;renderDays();changed();});
function moveWeek(n){const next=addDays(state.week,n);if(!parseDate(next)||next<'1900-01-01'||next>'9998-12-31')return;state.week=next;$('week').value=state.week;renderDays();changed();}
$('previous').onclick=()=>moveWeek(-7);$('next').onclick=()=>moveWeek(7);
$('all').onclick=()=>{state.selected=[...state.names];renderEmployees();changed();};$('none').onclick=()=>{state.selected=[];renderEmployees();changed();};
$('back').onclick=()=>{page--;render();};$('forward').onclick=()=>{page++;render();};
window.addEventListener('beforeprint',()=>{$('printPages').innerHTML=printBatch().map(printHTML).join('');});
window.addEventListener('afterprint',()=>{$('printPages').innerHTML='';});
$('print').onclick=()=>{if(!jobs().length)return;$('printPages').innerHTML=printBatch().map(printHTML).join('');window.print();};
$('manage').onclick=()=>{$('names').value=state.names.join('\n');$('editError').textContent='';$('editor').showModal();};$('cancel').onclick=()=>$('editor').close();
$('editForm').onsubmit=e=>{e.preventDefault();const names=$('names').value.split(/\r?\n/).map(n=>n.trim()).filter(Boolean);if(!names.length||names.length>250||names.some(n=>n.length>100)){$('editError').textContent='Enter 1–250 names, each no longer than 100 characters.';return;}if(new Set(names.map(n=>n.toLowerCase())).size!==names.length){$('editError').textContent='Each name must be unique. Please remove duplicates.';return;}state.selected=names.filter(n=>state.selected.includes(n)||!state.names.includes(n));state.names=names;renderEmployees();changed();$('editor').close();};
